// ════════════════════════════════════════════
// 꿈속 탐험가 — 공용 도트 스프라이트 데이터
// dream-card.html(게임)과 pixel-gallery.html(갤러리)이 함께 사용.
// 도트를 고칠 땐 여기 한 곳만 수정하면 양쪽에 반영됨.
// 규칙: 16×18 그리드, 외곽선 + 3단 명암, '.' = 투명.
// ════════════════════════════════════════════

var SPRITE_DATA = {
  // 탐험가: 노란 모자 + 파란 셔츠 소년
  explorer: {
    pal: { K:"#1d1433", Y:"#ffe27a", y:"#f0b83c", d:"#c08a22",
           s:"#ffd9ac", E:"#33284a", B:"#2b57c8", b:"#5480ea", P:"#6b4526" },
    rows: [
      "................",
      "....KKKKKKK.....",
      "...KYYyyyyyK....",
      "..KYyyyyyyydK...",
      "..KyyyyyyyyddK..",
      ".KKKKKKKKKKKKKK.",
      "..KssssssssK....",
      "..KsEssssEsK....",
      "..KssssssssK....",
      "..KssKKKsssK....",
      "...KssssssK.....",
      "..KBBBBBBBBK....",
      ".KsKBbbbbbBKsK..",
      ".KsKBbBBBbBKsK..",
      "..KKBBBBBBBKK...",
      "...KPPPKPPPK....",
      "...KPPK.KPPK....",
      "..KKKKK.KKKKK...",
    ],
  },
  // 몽상가: 보라 후드 마법사 + 수정구
  dreamer: {
    pal: { K:"#1c1030", p:"#6a35c0", P:"#916ae8", d:"#4b2390",
           s:"#ffd9ac", E:"#33284a", C:"#b8f0ff", c:"#5fb8e8" },
    rows: [
      "....KKKKKKKK....",
      "...KppppppppK...",
      "..KpPPppppppK...",
      "..KppppppppppK..",
      ".KpKssssssKpK...",
      ".KpKsEssEsKpK...",
      ".KpKssssssKpK...",
      "..KKssssssKK....",
      "..KpppppppppK...",
      ".KpKpppppppKpK..",
      ".KpKpPPPpppKpK..",
      "..KppKCcKppK....",
      "..KppKcCKppK....",
      "..KpppKKpppK....",
      ".KpppppppppppK..",
      ".KpppdpppdpppK..",
      ".KKKKKKKKKKKKK..",
      "................",
    ],
  },
  // 악몽사: 뿔 + 검보라 머리 + 붉은 눈의 전투사
  dark: {
    pal: { K:"#150c22", H:"#e8dcc0", h:"#34254d", l:"#5a4185",
           s:"#f0cba0", v:"#ff4455", R:"#8a1830", r:"#b03050", D:"#2a1030" },
    rows: [
      "...KK......KK...",
      "...KHK....KHK...",
      "..KKKKKKKKKKKK..",
      "..KhlhhhhhhhhK..",
      "..KhhhhhhhhhhK..",
      "..KhhhhhhhhhhK..",
      "...KsvssssvsK...",
      "...KssssssssK...",
      "...KssKKKsssK...",
      "....KssssssK....",
      "..KRRRRRRRRRRK..",
      ".KsKRrRRRRrRKsK.",
      ".KsKRRRRRRRRKsK.",
      "..KKRRRRRRRRKK..",
      "...KDDDKDDDK....",
      "...KDDK.KDDK....",
      "..KKKKK.KKKKK...",
      "................",
    ],
  },
};

// ── 적 도트 스프라이트 (16×18, 외곽선 + 3단 명암) ──

Object.assign(SPRITE_DATA, {
  // 정체모를 그림자 — 보라 유령, 붉은 눈
  shadow: {
    pal:{ K:"#0a0616", s:"#221636", b:"#3a2757", h:"#523a78", E:"#ff5566", W:"#ffd0d0" },
    rows:[
      "................",
      ".....KKKKKK.....",
      "...KKhhhhhhKK...",
      "..KhhhbbbbhhhK..",
      "..KhbbbbbbbbhK..",
      ".KhbbbbbbbbbbhK.",
      ".KbbbbbbbbbbbbK.",
      ".KbbEEbbbbEEbbK.",
      ".KbEEEEbbEEEEbK.",
      ".KbEEEEbbEEEEbK.",
      ".KbbEEbbbbEEbbK.",
      ".KbbbbbbbbbbbbK.",
      ".KbbbbbWWbbbbbK.",
      ".KsbbbbbbbbbbsK.",
      ".KsbbbbbbbbbbsK.",
      ".KbbKbbbbbbKbbK.",
      "..KbK.KbbK.KbK..",
      "...K...KK...K...",
    ],
  },
  // 말하는 시험지 — 하얀 종이, 붉은 채점 표시
  testpaper: {
    pal:{ K:"#3a3a4a", P:"#ffffff", p:"#dcdcec", d:"#b4b4c8", E:"#2a2a3a", R:"#ff3333" },
    rows:[
      "..KKKKKKKKKKKK..",
      ".KPPPPPPPPPPPPK.",
      ".KPPPPPPPPPPPPK.",
      ".KPPRPPPPPPRPPK.",
      ".KPPRRPPPPRRPPK.",
      ".KPPPPPPPPPPPPK.",
      ".KPEEPPPPPPEEPK.",
      ".KPEEPPPPPPEEPK.",
      ".KPPPPPPPPPPPPK.",
      ".KPPPPRRRRPPPPK.",
      ".KPPPRPPPPRPPPK.",
      ".KPPPPPPPPPPPPK.",
      ".KPPdPPPPPPdPPK.",
      ".KPdPPPPPPPPdPK.",
      ".KPPPPPPPPPPPPK.",
      ".KppppppppppppK.",
      ".KKKKKKKKKKKKKK.",
      "................",
    ],
  },
  // 화난 양말 — 줄무늬, 성난 눈
  sock: {
    pal:{ K:"#2a2438", W:"#f4efe2", s:"#cec7b2", b:"#5a8ad0", R:"#e0403f", E:"#2a2438", m:"#b02828" },
    rows:[
      "..KKKKK.........",
      "..KWWWWK........",
      "..KbbbbK........",
      "..KRWWRK........",
      "..KWEEWK........",
      "..KWWWWK........",
      "..KWmmWK........",
      "..KWWWWK........",
      "..KbbbbK........",
      "..KWWWWK........",
      "..KWWWWK........",
      "..KWWWWKKKKK....",
      "..KsWWWWWWWWK...",
      "..KWWWWWWWWWK...",
      "..KbbbbbbbbbK...",
      "..KWWWWWWWssK...",
      "..KKKKKKKKKKK...",
      "................",
    ],
  },
  // 초콜릿 괴물 — 갈색 초코바, 격자무늬
  choco: {
    pal:{ K:"#2a1608", b:"#6a3a1a", d:"#4a2610", h:"#8a5a2a", E:"#fff0d0", m:"#3a1e0e" },
    rows:[
      "................",
      "..KKKKKKKKKKKK..",
      ".KhbbbbbbbbbbhK.",
      ".KbdbbdbbdbbdbK.",
      ".KbbbbbbbbbbbbK.",
      ".KbEEbbbbbbEEbK.",
      ".KbEEbbbbbbEEbK.",
      ".KbdbbdbbdbbdbK.",
      ".KbbbbbbbbbbbbK.",
      ".KbbbmmmmmmbbbK.",
      ".KbbmEEEEEEmbbK.",
      ".KbbbmmmmmmbbbK.",
      ".KbdbbdbbdbbdbK.",
      ".KbbbbbbbbbbbbK.",
      ".KhbbbbbbbbbbhK.",
      ".KKKKKKKKKKKKKK.",
      "................",
      "................",
    ],
  },
  // 웃는 브로콜리 — 초록 송이 + 연한 줄기
  broccoli: {
    pal:{ K:"#12280e", g:"#3c7e30", h:"#58a842", s:"#d2dca8", t:"#aebd82", m:"#0e2208", E:"#0e2208" },
    rows:[
      "................",
      "....KKKKKK......",
      "..KKgggggggKK...",
      ".KggghhggghhggK.",
      ".KghgggggggghgK.",
      ".KgEEggggEEgggK.",
      ".KggggggggggggK.",
      ".KggmggggggmggK.",
      ".KgggmmmmmmgggK.",
      ".KgghhgggghhggK.",
      "...KssssssK.....",
      "...KsttttsK.....",
      "...KssttssK.....",
      "...KssssssK.....",
      "...KsttttsK.....",
      "...KssssssK.....",
      "...KKKKKKKK.....",
      "................",
    ],
  },
  // 아기 브로콜리 — 작고 귀여운 새싹
  broccoli_baby: {
    pal:{ K:"#12280e", g:"#3c7e30", s:"#d2dca8", m:"#0e2208", E:"#0e2208" },
    rows:[
      "................",
      "................",
      "................",
      ".....KKKK.......",
      "....KgEEgK......",
      "....KggggK......",
      "....KgmmgK......",
      ".....KssK.......",
      ".....KssK.......",
      ".....KKKK.......",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  // 거대해진 친구 — 파란 옷 거인
  giantfriend: {
    pal:{ K:"#14102a", r:"#8a5a30", s:"#f6cfa2", c:"#ff9d9d", E:"#14102a", m:"#b83a4a", b:"#2f6ad0", d:"#1f4aa0", y:"#ffe27a" },
    rows:[
      "................",
      ".....KKKK.......",
      "....KrrrrrrK....",
      "...KrrssssrrK...",
      "..KrssssssssrK..",
      "..KssEssssEssK..",
      "..KssssssssssK..",
      "..KscmmmmmmcsK..",
      "..KssmmmmmmssK..",
      "...KssssssssK...",
      "..KKKKKKKKKKKK..",
      ".KbbbbbbbbbbbbK.",
      ".KyyyyyyyyyyyyK.",
      ".KsbdbbbbbbdbsK.",
      ".KKbbbbbbbbbbKK.",
      "..KssK..KssK....",
      "..KssK..KssK....",
      "..KKKK..KKKK....",
    ],
  },
  // 이빨 빠진 피아노 — 검은 몸통 + 흰 건반 + 검은 건반(2-3 배열) + 빠진 이빨
  piano: {
    pal:{ K:"#12121c", b:"#22222e", W:"#f2f2f8", E:"#ff5566" },
    rows:[
      "................",
      ".KKKKKKKKKKKKKK.",
      ".KbbbbbbbbbbbbK.",
      ".KbEEbbbbbbEEbK.",
      ".KbbbbbbbbbbbbK.",
      ".KKKKKKKKKKKKKK.",
      ".KWbWbWWbWbWbWK.",
      ".KWbWbWWbWbWbWK.",
      ".KWKWKbbKWKWKWK.",
      ".KWKWKbbKWKWKWK.",
      ".KWWWWbbWWWWWWK.",
      ".KWWWWWWWWWWWWK.",
      ".KKKKKKKKKKKKKK.",
      "..KbbK..KbbK....",
      "..KbbK..KbbK....",
      "..KKKK..KKKK....",
      "................",
      "................",
    ],
  },
  // 숙제 문어 — 보라 문어 + 하양 종이
  octopus: {
    pal:{ K:"#2a0e28", p:"#b0449a", d:"#822870", h:"#d874c0", E:"#ffffff", W:"#3a1038" },
    rows:[
      "................",
      "....KKKKKK......",
      "..KKpphhppKK....",
      ".KphhpppppphpK..",
      ".KphpppppppphK..",
      ".KpEEppppEEpppK.",
      ".KpWWppppWWpppK.",
      ".KppppppppppppK.",
      ".KppppddddppppK.",
      ".KpdppppppppdpK.",
      ".KppppppppppppK.",
      ".KppppppppppppK.",
      ".KpKppKppKppKpK.",
      ".KpKppKppKppKpK.",
      "..KK.KK.KK.KK...",
      "................",
      "................",
      "................",
    ],
  },
  // 한밤의 냉장고 — 하늘색 냉장고, 손잡이
  fridge: {
    pal:{ K:"#1a2a34", W:"#d8ecf4", s:"#a8ccdc", d:"#88b0c4", E:"#1a2a34", H:"#5a7a8a" },
    rows:[
      "..KKKKKKKKKKKK..",
      ".KWWWWWWWWWWWWK.",
      ".KWWWWWWWWWWHWK.",
      ".KWEWWWWWWEWHWK.",
      ".KWWWWWWWWWWHWK.",
      ".KWWWWddWWWWWWK.",
      ".KWWWWWWWWWWWWK.",
      ".KKKKKKKKKKKKKK.",
      ".KWWWWWWWWWWHWK.",
      ".KWWWWWWWWWWHWK.",
      ".KsWWWWWWWWWWWK.",
      ".KWWWWWWWWWWWWK.",
      ".KWWWWWWWWWWWWK.",
      ".KWWWWWWWWWWWWK.",
      ".KWWWWWWWWWWWWK.",
      ".KKKKKKKKKKKKKK.",
      "..KK......KK....",
      "................",
    ],
  },
  // 꼬마 알람 — 작은 알람시계
  mini_alarm: {
    pal:{ K:"#2a1810", y:"#ffd23a", d:"#c89020", W:"#fff6d8", E:"#2a1810", b:"#e05030" },
    rows:[
      "................",
      "................",
      "....KK....KK....",
      "...KbK....KbK...",
      "....KKKKKKKK....",
      "...KyyyyyyyyK...",
      "..KyWWWWWWWWyK..",
      "..KyWEWWWWEWyK..",
      "..KyWWWWWWWWyK..",
      "..KyWWWddWWWyK..",
      "..KyWWWWWWWWyK..",
      "...KyyyyyyyyK...",
      "....KddddddK....",
      "...KK....KK.....",
      "................",
      "................",
      "................",
      "................",
    ],
  },
  // 악몽의 알람시계 (보스) — 커다란 알람시계, 화난 얼굴
  alarm_boss: {
    pal:{ K:"#1a0e08", y:"#ffcc22", d:"#c08010", h:"#ffe680", W:"#fff6d8", E:"#1a0e08", b:"#e0402a", R:"#ff5566" },
    rows:[
      "...KKK....KKK...",
      "..KbbbK..KbbbK..",
      "..KbbbKKKKbbbK..",
      "...KKyyyyyyKK...",
      "..KyyhhhhhhyyK..",
      ".KyhhWWWWWWhhyK.",
      ".KyhWWWWWWWWhyK.",
      ".KyWWEEWWEEWWyK.",
      ".KyWWEEWWEEWWyK.",
      ".KyWWWWWWWWWWyK.",
      ".KyWWRRRRRRWWyK.",
      ".KyWRRWWWWRRWyK.",
      ".KyhWWWWWWWWhyK.",
      ".KyyhhhhhhhhyyK.",
      "..KKyyyyyyyyKK..",
      "...KdddddddK....",
      "..KK.KKKK.KK....",
      "................",
    ],
  },
});

// 분류 (갤러리에서 캐릭터/적 나눠서 보여주기)
var SPRITE_GROUPS = {
  characters: ["explorer","dreamer","dark"],
  enemies: ["shadow","testpaper","sock","choco","broccoli","broccoli_baby","giantfriend","piano","octopus","fridge","mini_alarm","alarm_boss"],
};

// 한글 이름 (갤러리 표시용)
var SPRITE_LABELS = {
  explorer:"탐험가",
  dreamer:"몽상가",
  dark:"악몽사",
  shadow:"정체모를 그림자",
  testpaper:"말하는 시험지",
  sock:"화난 양말",
  choco:"초콜릿 괴물",
  broccoli:"웃는 브로콜리",
  broccoli_baby:"아기 브로콜리",
  giantfriend:"거대해진 친구",
  piano:"이빨 빠진 피아노",
  octopus:"숙제 문어",
  fridge:"한밤의 냉장고",
  mini_alarm:"꼬마 알람",
  alarm_boss:"악몽의 알람시계"
};
